apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: channel-carrier-allchannel
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: channel-carrier-allchannel
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/fabric-channel-create   
  values:
    metadata:
      namespace: carrier-net
      network:
        version: 2.2.2
      images:
        fabrictools: ghcr.io/hyperledger/bevel-fabric-tools:2.2.2
        alpineutils: ghcr.io/hyperledger/bevel-alpine:latest

    peer:
      name: peer0
      address: peer0.carrier-net:7051
      localmspid: carrierMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://a2b62cfc6ed514bcbbb77908d294b9f3-885673975.us-east-1.elb.amazonaws.com:20001
      authpath: localcarrier
      adminsecretprefix: secretsv2/data/carrier/peerOrganizations/carrier-net/users/admin
      orderersecretprefix: secretsv2/data/carrier/peerOrganizations/carrier-net/orderer 
      serviceaccountname: vault-auth
      type: hashicorp
      imagesecretname: regcred
    
    channel:
      name: allchannel
    orderer:
      address: orderer1.supplychain-net:7050
    channeltx: |-
      CtkDChgKFggCGgYIgbvkswYiCmFsbGNoYW5uZWwSvAMKuQMKCmFsbGNoYW5uZWwSRhI0CgtBcHBs
      aWNhdGlvbhIlEg4KCmNhcnJpZXJNU1ASABITCg9tYW51ZmFjdHVyZXJNU1ASABoOCgpDb25zb3J0
      aXVtEgAa4gIStgIKC0FwcGxpY2F0aW9uEqYCCAESDgoKY2Fycmllck1TUBIAEhMKD21hbnVmYWN0
      dXJlck1TUBIAGiQKDENhcGFiaWxpdGllcxIUEgoKCAoEVjJfMBIAGgZBZG1pbnMiIgoHUmVhZGVy
      cxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZB
      ZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiLAoLRW5kb3JzZW1lbnQS
      HRITCAMSDwoLRW5kb3JzZW1lbnQQAhoGQWRtaW5zIjUKFExpZmVjeWNsZUVuZG9yc2VtZW50Eh0S
      EwgDEg8KC0VuZG9yc2VtZW50EAIaBkFkbWlucyoGQWRtaW5zGicKCkNvbnNvcnRpdW0SGRIXChVT
      dXBwbHlDaGFpbkNvbnNvcnRpdW0=
