apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: anchorpeer-allchannel-carrier
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: anchorpeer-allchannel-carrier
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/fabric-anchorpeer
  values:
    metadata:
      namespace: carrier-net
      network:
        version: 2.2.2
      images:
        fabrictools: ghcr.io/hyperledger/bevel-fabric-tools:2.2.2
        alpineutils: ghcr.io/hyperledger/bevel-alpine:latest

    peer:
      name: peer0
      address: peer0.carrier-net:7051
      localmspid: carrierMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://a144fe93f77d84e16b9e75df6266c7d4-709105725.us-east-1.elb.amazonaws.com:20001
      authpath: localcarrier
      adminsecretprefix: secretsv2/data/carrier/peerOrganizations/carrier-net/users/admin
      orderersecretprefix: secretsv2/data/carrier/peerOrganizations/carrier-net/orderer
      serviceaccountname: vault-auth
      type: hashicorp
    
      imagesecretname: regcred
      

    channel:
      name: allchannel      
    orderer:
      address: orderer1.supplychain-net:7050
    anchorstx: |-
      CrcCChgKFggCGgYI2IjqswYiCmFsbGNoYW5uZWwSmgIKlwIKCmFsbGNoYW5uZWwSYxJhCgtBcHBs
      aWNhdGlvbhJSCAESTgoKY2Fycmllck1TUBJAGgcKA01TUBIAIgsKB1JlYWRlcnMSACILCgdXcml0
      ZXJzEgAiCgoGQWRtaW5zEgAiDwoLRW5kb3JzZW1lbnQSABqjARKgAQoLQXBwbGljYXRpb24SkAEI
      ARKLAQoKY2Fycmllck1TUBJ9CAEaMQoLQW5jaG9yUGVlcnMSIhIYChYKEXBlZXIwLmNhcnJpZXIt
      bmV0EIs3GgZBZG1pbnMaBwoDTVNQEgAiCwoHUmVhZGVycxIAIgsKB1dyaXRlcnMSACIKCgZBZG1p
      bnMSACIPCgtFbmRvcnNlbWVudBIAKgZBZG1pbnM=

