apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: store-vaultk8s-job
  namespace: store-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: store-vaultk8s-job
  interval: 1m
  chart:
   spec:
    chart: platforms/shared/charts/bevel-vault-mgmt
    sourceRef:
      kind: GitRepository
      name: flux-dev
      namespace: flux-dev
  values:
    nameOverride: store-vaultk8s-job
    global:
      serviceAccountName: vault-auth
      cluster:
        cloudNativeServices: false
        kubernetesUrl: https://7F85BF539820184D713165B6CDBBC7AF.gr7.us-east-1.eks.amazonaws.com
      vault:
        type: hashicorp
        role: vault-role
        address: http://a2b62cfc6ed514bcbbb77908d294b9f3-885673975.us-east-1.elb.amazonaws.com:20001
        authPath: devstore
        network: fabric
        secretEngine: secretsv2
        secretPrefix: "data/store"
        tls:
    image:
      repository: ghcr.io/hyperledger/bevel-alpine
      tag: latest
      pullSecret: "regcred"
