apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: carrier-net-ca-tools
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: carrier-net-ca-tools
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/fabric-catools
  values:
    metadata:
      namespace: carrier-net
      name: ca-tools
      component_type: peer
      org_name: carrier
      proxy: none
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    replicaCount: 1

    image:
      alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
      catools: ghcr.io/hyperledger/bevel-fabric-ca-tools:1.2.1
      pullPolicy: IfNotPresent
    
    storage:
      storageclassname: carrier-bevel-storageclass
      storagesize: 512Mi
    
    vault:
      role: vault-role
      address: http://a2b62cfc6ed514bcbbb77908d294b9f3-885673975.us-east-1.elb.amazonaws.com:20001
      authpath: localcarrier
      secretusers: secretsv2/data/carrier/peerOrganizations/carrier-net/users
      secretorderer: secretsv2/data/carrier/peerOrganizations/carrier-net/orderers
      secretpeer: secretsv2/data/carrier/peerOrganizations/carrier-net/peers
      secretpeerorderertls: secretsv2/data/carrier/peerOrganizations/carrier-net/orderer/tls
      secretcert: secretsv2/data/carrier/peerOrganizations/carrier-net/ca?ca.carrier-net-cert.pem
      secretkey: secretsv2/data/carrier/peerOrganizations/carrier-net/ca?carrier-net-CA.key
      secretcouchdb: secretsv2/data/carrier/credentials/carrier-net/couchdb/carrier
      secretconfigfile: secretsv2/data/carrier/peerOrganizations/carrier-net/msp/config
      serviceaccountname: vault-auth
      type: hashicorp
      imagesecretname: regcred
    
    healthcheck: 
      retries: 10
      sleepTimeAfterError: 2

    
    org_data:
      external_url_suffix: develop.local.com
      component_subject: O=Carrier,OU=Carrier,L=51.50/-0.13/London,C=GB
      cert_subject: O=Carrier/OU=Carrier/L=51.50,-0.13,London/C=GB
      component_country: GB
      component_state: London
      component_location: London
      ca_url: ca.carrier-net:7054

    orderers:
      name: orderer1-
    orderers_info:
      - name: orderer1
        path: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBRENDQWFhZ0F3SUJBZ0lVVFlwVmtuSTVlWDd4L29rOHNndnpOaWFROFBjd0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05NalF3TmpJME1EazFNRFUyV2hjTk1qY3dOREUwTURrMU1EVTJXakJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJPQWdlTk1lN2FuSk9ReW1KSnBqWHVLUFd4azFaQ3ZMQldSb2w2RnBRRU0xQmlraHFIaEQKVEc5WVBmY2lzT21yK3dzL2FSYWlTSDhrQytkUTZOOEQzWU9qUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU1ZJdWU1NW9ieTlJUFVxRWhocWF0K1V0anRaVEFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlFQTJmUEhyL0VMNlZlcEJ6dXp2NFpMeUxFaFErTXNVMFR5L3h1YnV0cGEKREo0Q0lDSGJGd3ZxVXJ2L0xzaWtKcEppS0U3Q00yYjhnYXlISGRZYkFXbzlLOFNGCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0="

    peers:
      name: peer0,-      
    peer_count: "1"
    users: 
      users_list: "W3sndXNlcic6IE5vbmUsICdpZGVudGl0eSc6ICd1c2VyMScsICdhdHRyaWJ1dGVzJzogW3sna2V5JzogJ2hmLlJldm9rZXInLCAndmFsdWUnOiAndHJ1ZSd9XX1d"
      users_identities: user1-
    checks:
      refresh_cert_value: False
      add_peer_value: False
